name: 'Install Erlang/OTP on macOS'
inputs:
  otp: # 25.3.2-1
    required: true
    type: string
  os:
    required: false
    type: string
    default: macos-12

runs:
  using: composite
  steps:
    - name: prepare
      shell: bash
      run: |
        brew install curl zip unzip gnu-sed automake libtool bison kerl wget
        echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
        git config --global credential.helper store

    - uses: actions/cache@v3
      id: cache
      with:
        path: ~/.kerl/${{ inputs.otp }}
        key: otp-install-${{ inputs.otp }}-${{ inputs.os }}

    - name: build erlang
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      env:
        OTP: ${{ inputs.otp }}
      run: |
        set -eux
        if [ ! -d $HOME/.kerl/$OTP ]; then
          kerl build git https://github.com/emqx/otp.git OTP-$OTP $OTP
          kerl install $OTP $HOME/.kerl/$OTP
        fi

    - name: install rebar3
      shell: bash
      run: |
        set -eux
        REBAR=$(brew --prefix)/bin/rebar3
        if [ ! -f $REBAR ]; then
          wget https://s3.amazonaws.com/rebar3/rebar3 -O $REBAR
          chmod +x $REBAR
        fi
