ARG FROM=ghcr.io/emqx/emqx-builder/5.1-3:1.14.5-25.3.2-1-amzn2
FROM ${FROM}

RUN alternatives --set python /usr/bin/python2 && \
    yum install -y libtool && \
    for f in /usr/share/aclocal/*.m4; do ln -s $f /usr/local/share/aclocal/$(basename $f).m4; done
