name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      branch_or_tag:
        required: false
      is_release:
        required: false
        default: false

jobs:
  mac:
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 25.3.2-2
          - 26.1.2-1
        os:
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch_or_tag }} # when input is not given, the event tag is used

      - uses: ./.github/actions/macos-erlang
        with:
          otp: ${{ matrix.otp }}
          os: ${{ matrix.os }}

      - name: build release
        run: |
          . $HOME/.kerl/${{ matrix.otp }}/activate
          env BUILD_RELEASE=1 ./build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            _packages/*.tar.gz
            _packages/*.tar.gz.sha256

  linux:
    strategy:
      fail-fast: false
      matrix:
        builder:
          - 5.1-3:1.14.5-25.3.2-1
          - 5.3-8:1.15.7-26.2.5-2
        arch:
          - amd64
          - arm64
        os:
          - ubuntu24.04
          - ubuntu22.04
          - ubuntu20.04
          - debian12
          - debian11
          - debian10
          - debian9
          - amzn2
          - amzn2023
          - el8
          - el9
          - alpine3.15.1
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/emqx/emqx-builder/${{ matrix.builder }}-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch_or_tag }} # when input is not given, the event tag is used

      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.arch }}

      - name: build release
        if: matrix.os == 'amzn2'
        run: |
          docker build --platform=linux/${{ matrix.arch }} --build-arg FROM=$IMAGE -t emqx-builder:amzn2 -f .ci/Dockerfile.amzn2 .
          docker run -i --rm --user 1001 -v $(pwd):/wd --workdir /wd --platform=linux/${{ matrix.arch }} -e BUILD_RELEASE=1 emqx-builder:amzn2 bash -euc './build.sh'

      - name: build release
        if: matrix.os != 'amzn2'
        run: |
          docker run -i --rm --user 1001 -v $(pwd):/wd --workdir /wd --platform=linux/${{ matrix.arch }} -e BUILD_RELEASE=1 $IMAGE bash -euc './build.sh'

      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            _packages/*.tar.gz
            _packages/*.tar.gz.sha256

  release:
    runs-on: ubuntu-latest
    needs:
      - mac
      - linux
    if: startsWith(github.ref, 'refs/tags/') || inputs.is_release == true
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: packages
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Erlang jq NIF ${{ github.event.inputs.branch_or_tag || github.ref_name }} Released
          tag_name: ${{ github.event.inputs.branch_or_tag || github.ref_name }}
          files: "packages/*"
